### ISSUE TITLE
I'm having trouble with mobile devices

### ISSUE THREAD

**Issue by n0sleeves** [jescalan/rupture#28]
I am using the Jeet framework with Stylus. I have @import "rupture" at the top of my Stylus as well as command line - stylus -u jeet -u rupture -w main.styl. 

Rupture is working on the my development laptop. When I resize the browser window, it's responding perfectly. However, when I go to test on iPhone, and a tablet, it doesn't appear to be working. I am testing with a simple Rupture mixin: 

+below(1200px)
    body
        background-image none
        background-color green

Btw, I am tabbing Stylus correctly, but this forum is stripping the spacing out. I have also tried +mobile() to no avail. Maybe I'm missing something.  Thanks for your help.

**Comment by Splendorr** [comment]
@n0sleeves Could you tell me what you did to solve this? I'm also having no luck getting Rupture to work on mobile devices.
