### ISSUE TITLE
no-conflict mode

### ISSUE THREAD

**Issue by BerkeleyTrue** [jescalan/rupture#76]
Would a PR adding a no-conflict mode be accepted?

**Comment by jescalan** [comment]
Yes it would!

**Comment by BerkeleyTrue** [comment]
Should I also remove `from-width` aliases or just namespace them as well?

As for the namespace, I was think r-between, r-above... How does that sound?

**Comment by jescalan** [comment]
Namespace them as well

It should be the full `rupture`, there are plenty of other libraries that start with "r"

**Comment by BerkeleyTrue** [comment]
Sure.
