### ISSUE TITLE
Fix not released, +below, +above, don't work.

### ISSUE THREAD

**Issue by zenopopovici** [jescalan/rupture#83]
https://github.com/jescalan/rupture/commit/752e56a1b3b48c6d8ddacd73c8f712430e60f615

**Comment by jescalan** [comment]
Hey there,

Sorry, could you add some more detail here? Are you saying that commit broke above and below? Also, details about what is broken would be appreciated - the tests are passing here but added a second set of parens around the query details. Are those parens invalid syntax?

**Comment by zenopopovici** [comment]
@jescalan From what I checked that commit didn't made it into the final release.  `@media ({condition})` must be replaced with `@media condition` in order for the media queries to work in Chrome.

**Comment by zenopopovici** [comment]
With **v0.7**
```
@media (only screen and (max-width: 1050px)) {
  .h-show-for-large-up {
    display: none !important;
  }
}
```
With **v.0.61**
```
@media only screen and (max-width: 1050px) {
  .h-show-for-large-up {
    display: none !important;
  }
}
```

**Comment by jescalan** [comment]
Ok, I'll roll that one back and re-release. Sorry about the oversight - this project is basically in maintenance mode, since I moved on from stylus a long time ago.

**Comment by jescalan** [comment]
Ok should be good to go `0.7.1` patch release rolls it back

**Comment by zenopopovici** [comment]
@jescalan A lot of us use it. Thanks for all your work.
